### ISSUE TITLE
ConfigurationError: Tool config file not found: ./config/migrated_tools_conf.xml

### ISSUE THREAD

**Issue by mictadlo** [fredhutchio/docker-galaxy#1]
Hi,
I run your Dockerfile in the following way:

```
docker run -p 8080:80 -p 8021:21 -p 8800:8800 --privileged=true -e DOCKER_PARENT=True -v /var/run/docker.sock:/var/run/docker.sock -v /home/galaxy/galaxy_storage2/:/export/ -e "GALAXY_CONFIG_ADMIN_USERS=m@..." -e "host=0.0.0.0" fredhutchio-galaxy-docker
```

However, I received the following error:

```
  usermod: no changes
  Starting main... done.
  Starting web1... done.
  Starting web2... done.
  Starting web3... done.
  ==> main.log <==
  python path is: /galaxy/stable/eggs/Babel-1.3-py2.7.egg, /galaxy/stable/eggs/pytz-2013.9-py2.7.egg, /galaxy/stable/eggs/mercurial-3.2.4-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/Mako-0.4.1-py2.7.egg, /galaxy/stable/eggs/numpy-1.6.0-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/kombu-3.0.24-py2.7.egg, /galaxy/stable/eggs/anyjson-0.3.3-py2.7.egg, /galaxy/stable/eggs/PyYAML-3.10-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/WebHelpers-1.3-py2.7.egg, /galaxy/stable/eggs/MarkupSafe-0.12-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/pycrypto-2.5-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/Cheetah-2.2.2-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/python_lzo-1.08_2.03_static-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/pysam-0.4.2_kanwei_b10f6e722e9a-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/bx_python-0.7.2-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/WebOb-0.8.5-py2.7.egg, /galaxy/stable/eggs/Routes-2.1-py2.7.egg, /galaxy/stable/eggs/repoze.lru-0.6-py2.7.egg, /galaxy/stable/eggs/amqp-1.4.6-py2.7.egg, /galaxy/stable/eggs/pexpect-2.4-py2.7.egg, /galaxy/stable/eggs/wchartype-0.1-py2.7.egg, /galaxy/stable/eggs/docutils-0.7-py2.7.egg, /galaxy/stable/eggs/PasteDeploy-1.5.0-py2.7.egg, /galaxy/stable/eggs/Paste-1.7.5.1-py2.7.egg, /galaxy/stable/lib, /usr/lib/python2.7, /usr/lib/python2.7/plat-x86_64-linux-gnu, /usr/lib/python2.7/lib-tk, /usr/lib/python2.7/lib-old, /usr/lib/python2.7/lib-dynload, /usr/local/lib/python2.7/dist-packages, /usr/lib/python2.7/dist-packages
  Traceback (most recent call last):
File "/galaxy/stable/lib/galaxy/webapps/galaxy/buildapp.py", line 64, in paste_app_factory
  app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
File "/galaxy/stable/lib/galaxy/app.py", line 38, in __init__
  self.config.check()
File "/galaxy/stable/lib/galaxy/config.py", line 616, in check
  raise ConfigurationError("Tool config file not found: %s" % path )
  ConfigurationError: Tool config file not found: ./config/migrated_tools_conf.xml
  Removing PID file main.pid

  ==> web1.log <==
  python path is: /galaxy/stable/eggs/Babel-1.3-py2.7.egg, /galaxy/stable/eggs/pytz-2013.9-py2.7.egg, /galaxy/stable/eggs/mercurial-3.2.4-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/Mako-0.4.1-py2.7.egg, /galaxy/stable/eggs/numpy-1.6.0-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/kombu-3.0.24-py2.7.egg, /galaxy/stable/eggs/anyjson-0.3.3-py2.7.egg, /galaxy/stable/eggs/PyYAML-3.10-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/WebHelpers-1.3-py2.7.egg, /galaxy/stable/eggs/MarkupSafe-0.12-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/pycrypto-2.5-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/Cheetah-2.2.2-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/python_lzo-1.08_2.03_static-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/pysam-0.4.2_kanwei_b10f6e722e9a-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/bx_python-0.7.2-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/WebOb-0.8.5-py2.7.egg, /galaxy/stable/eggs/Routes-2.1-py2.7.egg, /galaxy/stable/eggs/repoze.lru-0.6-py2.7.egg, /galaxy/stable/eggs/amqp-1.4.6-py2.7.egg, /galaxy/stable/eggs/pexpect-2.4-py2.7.egg, /galaxy/stable/eggs/wchartype-0.1-py2.7.egg, /galaxy/stable/eggs/docutils-0.7-py2.7.egg, /galaxy/stable/eggs/PasteDeploy-1.5.0-py2.7.egg, /galaxy/stable/eggs/Paste-1.7.5.1-py2.7.egg, /galaxy/stable/lib, /usr/lib/python2.7, /usr/lib/python2.7/plat-x86_64-linux-gnu, /usr/lib/python2.7/lib-tk, /usr/lib/python2.7/lib-old, /usr/lib/python2.7/lib-dynload, /usr/local/lib/python2.7/dist-packages, /usr/lib/python2.7/dist-packages
  Traceback (most recent call last):
File "/galaxy/stable/lib/galaxy/webapps/galaxy/buildapp.py", line 64, in paste_app_factory
  app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
File "/galaxy/stable/lib/galaxy/app.py", line 38, in __init__
  self.config.check()
File "/galaxy/stable/lib/galaxy/config.py", line 616, in check
  raise ConfigurationError("Tool config file not found: %s" % path )
  ConfigurationError: Tool config file not found: ./config/migrated_tools_conf.xml
  Removing PID file web1.pid

  ==> web2.log <==
  python path is: /galaxy/stable/eggs/Babel-1.3-py2.7.egg, /galaxy/stable/eggs/pytz-2013.9-py2.7.egg, /galaxy/stable/eggs/mercurial-3.2.4-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/Mako-0.4.1-py2.7.egg, /galaxy/stable/eggs/numpy-1.6.0-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/kombu-3.0.24-py2.7.egg, /galaxy/stable/eggs/anyjson-0.3.3-py2.7.egg, /galaxy/stable/eggs/PyYAML-3.10-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/WebHelpers-1.3-py2.7.egg, /galaxy/stable/eggs/MarkupSafe-0.12-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/pycrypto-2.5-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/Cheetah-2.2.2-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/python_lzo-1.08_2.03_static-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/pysam-0.4.2_kanwei_b10f6e722e9a-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/bx_python-0.7.2-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/WebOb-0.8.5-py2.7.egg, /galaxy/stable/eggs/Routes-2.1-py2.7.egg, /galaxy/stable/eggs/repoze.lru-0.6-py2.7.egg, /galaxy/stable/eggs/amqp-1.4.6-py2.7.egg, /galaxy/stable/eggs/pexpect-2.4-py2.7.egg, /galaxy/stable/eggs/wchartype-0.1-py2.7.egg, /galaxy/stable/eggs/docutils-0.7-py2.7.egg, /galaxy/stable/eggs/PasteDeploy-1.5.0-py2.7.egg, /galaxy/stable/eggs/Paste-1.7.5.1-py2.7.egg, /galaxy/stable/lib, /usr/lib/python2.7, /usr/lib/python2.7/plat-x86_64-linux-gnu, /usr/lib/python2.7/lib-tk, /usr/lib/python2.7/lib-old, /usr/lib/python2.7/lib-dynload, /usr/local/lib/python2.7/dist-packages, /usr/lib/python2.7/dist-packages
  Traceback (most recent call last):
File "/galaxy/stable/lib/galaxy/webapps/galaxy/buildapp.py", line 64, in paste_app_factory
  app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
File "/galaxy/stable/lib/galaxy/app.py", line 38, in __init__
  self.config.check()
File "/galaxy/stable/lib/galaxy/config.py", line 616, in check
  raise ConfigurationError("Tool config file not found: %s" % path )
  ConfigurationError: Tool config file not found: ./config/migrated_tools_conf.xml
  Removing PID file web2.pid

  ==> web3.log <==
  python path is: /galaxy/stable/eggs/Babel-1.3-py2.7.egg, /galaxy/stable/eggs/pytz-2013.9-py2.7.egg, /galaxy/stable/eggs/mercurial-3.2.4-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/Mako-0.4.1-py2.7.egg, /galaxy/stable/eggs/numpy-1.6.0-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/kombu-3.0.24-py2.7.egg, /galaxy/stable/eggs/anyjson-0.3.3-py2.7.egg, /galaxy/stable/eggs/PyYAML-3.10-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/WebHelpers-1.3-py2.7.egg, /galaxy/stable/eggs/MarkupSafe-0.12-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/pycrypto-2.5-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/Cheetah-2.2.2-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/python_lzo-1.08_2.03_static-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/pysam-0.4.2_kanwei_b10f6e722e9a-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/bx_python-0.7.2-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg, /galaxy/stable/eggs/WebOb-0.8.5-py2.7.egg, /galaxy/stable/eggs/Routes-2.1-py2.7.egg, /galaxy/stable/eggs/repoze.lru-0.6-py2.7.egg, /galaxy/stable/eggs/amqp-1.4.6-py2.7.egg, /galaxy/stable/eggs/pexpect-2.4-py2.7.egg, /galaxy/stable/eggs/wchartype-0.1-py2.7.egg, /galaxy/stable/eggs/docutils-0.7-py2.7.egg, /galaxy/stable/eggs/PasteDeploy-1.5.0-py2.7.egg, /galaxy/stable/eggs/Paste-1.7.5.1-py2.7.egg, /galaxy/stable/lib, /usr/lib/python2.7, /usr/lib/python2.7/plat-x86_64-linux-gnu, /usr/lib/python2.7/lib-tk, /usr/lib/python2.7/lib-old, /usr/lib/python2.7/lib-dynload, /usr/local/lib/python2.7/dist-packages, /usr/lib/python2.7/dist-packages
  Traceback (most recent call last):
File "/galaxy/stable/lib/galaxy/webapps/galaxy/buildapp.py", line 64, in paste_app_factory
  app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
File "/galaxy/stable/lib/galaxy/app.py", line 38, in __init__
  self.config.check()
File "/galaxy/stable/lib/galaxy/config.py", line 616, in check
  raise ConfigurationError("Tool config file not found: %s" % path )
  ConfigurationError: Tool config file not found: ./config/migrated_tools_conf.xml
  Removing PID file web3.pid
```

What did I do wrong?

Mic

**Comment by bcclaywell** [comment]
@mictadlo I'm so sorry, I completely missed this issue notification! This Docker image is somewhat specific to our setup but it should work in other situations with some gentle nudging. Do you still need help? Just let me know!
